# Generated by Django 5.2.13 on 2026-05-05 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commande_lignecommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commande'),
        ),
    ]
