# Generated by Django 5.2.13 on 2026-05-11 20:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_commande_montant_paye_commande_montant_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piece',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pieces/'),
        ),
        migrations.AddField(
            model_name='reparation',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reparation',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reparation',
            name='statut',
            field=models.CharField(default='en attente', max_length=50),
        ),
        migrations.AddField(
            model_name='reparation',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('partiellement_paye', 'Partiellement payé'), ('paye', 'Payé')], default='non_paye', max_length=20),
        ),
        migrations.AlterField(
            model_name='piece',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='pieces',
            field=models.ManyToManyField(blank=True, to='core.piece'),
        ),
        migrations.CreateModel(
            name='PaiementReparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('methode', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('reparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.reparation')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.piece')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.panier')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
