# Generated by Django 5.2.13 on 2026-05-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_adresse_client_date_creation_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparation',
            name='date_rendezvous',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reparation',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
