# Generated by Django 5.2.13 on 2026-06-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reparation_date_rendezvous_reparation_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparation',
            name='statut',
            field=models.CharField(choices=[('rendez_vous', 'Rendez-vous'), ('en attente', 'En attente'), ('en cours', 'En cours'), ('terminee', 'Terminée')], default='en attente', max_length=50),
        ),
    ]
