# Generated by Django 5.2.13 on 2026-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reparation_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=120)),
                ('texte', models.TextField()),
                ('note', models.IntegerField(default=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('actif', 'Actif'), ('archive', 'Archivé')], default='en_attente', max_length=20)),
            ],
        ),
    ]
