# Generated by Django 5.2.13 on 2026-06-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_temoignage'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='categorie',
            field=models.CharField(choices=[('pneu', '🛞 Pneus'), ('frein', '🛑 Freinage'), ('suspension', '🔧 Suspensions'), ('jante', '⚙️ Jantes & roues'), ('electrique', '🔋 Électrique'), ('moteur', '🔧 Moteur'), ('transmission', '⛓️ Transmission'), ('carrosserie', '🎨 Carrosserie'), ('autre', '📦 Autre')], default='autre', max_length=20),
        ),
    ]
